#!/usr/bin/env zsh

###############################################################################
# Application Settings
###############################################################################

# Note: LinearMouse and Rectangle configs are now managed by the apps/ stow package
# They are automatically symlinked when you run ./install.sh

# Uncomment below to enable custom DOTA 2 shortcuts
# defaults write com.apple.universalaccess com.apple.custommenu.apps -array-add "com.valvesoftware.dota2"
# defaults write com.valvesoftware.dota2 NSUserKeyEquivalents -dict Close "@~$\\U00e5" "Quit Dota 2" = "@$\\U00e5"