#!/bin/sh

###############################################################################
# DOTA 2
###############################################################################

# Add to enable customer shortcuts
# defaults write com.apple.universalaccess com.apple.custommenu.apps -array-add "com.valvesoftware.dota2"
# Rewrite quit shortcuts
# defaults write com.valvesoftware.dota2 NSUserKeyEquivalents -dict Close "@~$\\U00e5" "Quit Dota 2" = "@$\\U00e5"

# Linear mouse settings
mkdir -p ~/.config/linearmouse
cp setup/linearmouse.json ~/.config/linearmouse/

# Rectangle mouse settings
mkdir -p ~/Library/Application\ Support/Rectangle
cp setup/RectangleConfig.json ~/Library/Application\ Support/Rectangle/