tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# Install bash and bash completions
brew "bash"
brew "bash-completion@2"

# Install git
brew "git"

# Install utilities
cask "rectangle"
cask "shottr"
cask "linearmouse"
# Go install AirpodsSanity from https://github.com/Gaulomatic/AirPodsSanity

# Install libraries
brew "molten-vk"

# Install applications
# cask "google-chrome"
cask "visual-studio-code"

# Other apps
cask "discord"
cask "steam"