#!/bin/sh

# Logging stuff.
function e_header()   { echo -e "\n\033[1m$@\033[0m"; }
function e_success()  { echo -e " \033[1;32m✔\033[0m  $@"; }
function e_error()    { echo -e " \033[1;31m✖\033[0m  $@"; }
function e_arrow()    { echo -e " \033[1;33m➜\033[0m  $@"; }

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install Homebrew.
if [[ ! "$(type -P brew)" ]]; then
  e_header "Installing Homebrew"
  true | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  # Add homebrew to path
  echo >> /Users/$(whoami)/.zprofile
  echo 'eval "$(`which brew` shellenv)"' >>/Users/$(whoami)/.zprofile
  eval "$($(which brew) shellenv)"
fi

e_header "Updating Homebrew"
brew doctor
brew update

# Note: macOS uses zsh by default since Catalina
# No need to install bash or change shell

# Ensure shell completions
brew completions link

# Install Homebrew recipes.
e_header "Installing apps and utilities"

# Install applications and utilies with homebrew
brew bundle install --file=$HOME/.dotfiles/Brewfile


# Finally clean brewup
brew cleanup
