#!/usr/bin/env bash

# Logging stuff.
function e_header()   { echo -e "\n\033[1m$@\033[0m"; }
function e_success()  { echo -e " \033[1;32m✔\033[0m  $@"; }
function e_error()    { echo -e " \033[1;31m✖\033[0m  $@"; }
function e_arrow()    { echo -e " \033[1;33m➜\033[0m  $@"; }

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install Homebrew.
if [[ ! "$(type -P brew)" ]]; then
  e_header "Installing Homebrew"
  true | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

e_header "Updating Homebrew"
brew doctor
brew update

if [ ! -f $(brew --prefix)/bin/bash ]; then
  # Bash 4
  brew install bash
  brew install bash-completion@2

  # Set new shell, Bash 4
  BASHPATH=$(brew --prefix)/bin/bash
  echo $BASHPATH | sudo tee -a /etc/shells
  chsh -s $BASHPATH # will set for current user only.
fi

# Install Homebrew recipes.
e_header "Installing apps and utilities"

# Install applications and utilies with homebrew
brew bundle install --file=$HOME/.dotfiles/setup/Brewfile


# Finally clean brewup
brew cleanup
