#!/usr/bin/env zsh

# Close any open System Settings panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Settings" to quit' || true

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until script has finished
# Store background process PID for cleanup
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
SUDO_KEEPALIVE_PID=$!

# Cleanup function to kill sudo keep-alive
cleanup() {
    kill "$SUDO_KEEPALIVE_PID" 2>/dev/null || true
}
trap cleanup EXIT INT TERM


###############################################################################
# General UI/UX
###############################################################################

# Setting keyboard layouts
defaults write NSGlobalDomain AppleLanguages -array "en-SE" "sv-SE"

# Disable shadows on screenshots
defaults write com.apple.screencapture disable-shadow -bool true

# Increasing the window resize speed for Cocoa applications"
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

# Speed up Mission Control animations
defaults write com.apple.dock expose-animation-duration -float 0.1

# Expanding the save and print panels by default"
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Set spaces to not automatically reorder
defaults write com.apple.dock "mru-spaces" -bool "false"

###############################################################################
# Trackpad, mouse, keyboard, and input"
###############################################################################

# Setting a blazingly fast keyboard repeat rate (ain't nobody got time for special chars while coding!)"
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# Trackpad behavior"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad DragLock -bool false
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Dragging -bool false
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -bool false
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadFiveFingerPinchGesture -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadFourFingerHorizSwipeGesture -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadFourFingerPinchGesture -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadFourFingerVertSwipeGesture -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadHandResting -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadHorizScroll -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadMomentumScroll -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadPinch -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRotate -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadScroll -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool false
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerTapGesture -bool false
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerVertSwipeGesture -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadTwoFingerDoubleTapGesture -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadTwoFingerFromRightEdgeSwipeGesture -int 3
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad USBMouseStopsTrackpad -bool false
# Disable swipe to go back/forward
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerHorizSwipeGesture -int 0
defaults write NSGlobalDomain AppleEnableSwipeNavigateWithScrolls -bool false

# Bluetooth mouse settings
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseButtonDivision -int 55
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseButtonMode -string TwoButton
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseHorizontalScroll -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseMomentumScroll -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseOneFingerDoubleTapGesture -bool false
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseTwoFingerDoubleTapGesture -int 3
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseTwoFingerHorizSwipeGesture -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseVerticalScroll -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse UserPreferences -bool true

# Setting trackpad & mouse speed to a preferred number"
defaults write -g com.apple.trackpad.scaling -float 3.5
defaults write -g com.apple.mouse.scaling -float 0.4

###############################################################################
# Control center
###############################################################################

# Menu bar
defaults write com.apple.controlcenter "NSStatusItem Preferred Position Battery" -int 144
defaults write com.apple.controlcenter "NSStatusItem Preferred Position BentoBox" -int 112
defaults write com.apple.controlcenter "NSStatusItem Preferred Position Clock" -int 92
defaults write com.apple.controlcenter "NSStatusItem Preferred Position Display" -int 215
defaults write com.apple.controlcenter "NSStatusItem Preferred Position FocusModes" -int 409
defaults write com.apple.controlcenter "NSStatusItem Preferred Position NowPlaying" -int 371
defaults write com.apple.controlcenter "NSStatusItem Preferred Position ScreenMirroring" -int 186
defaults write com.apple.controlcenter "NSStatusItem Preferred Position Sound" -int 411
defaults write com.apple.controlcenter "NSStatusItem Preferred Position WiFi" -int 171
defaults write com.apple.controlcenter "NSStatusItem Visible AudioVideoModule" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Battery" -bool true
defaults write com.apple.controlcenter "NSStatusItem Visible BentoBox" -bool true
defaults write com.apple.controlcenter "NSStatusItem Visible Clock" -bool true
defaults write com.apple.controlcenter "NSStatusItem Visible Display" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible FaceTime" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible FocusModes" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Item-0" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Item-1" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Item-2" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Item-3" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Item-4" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Item-5" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Item-6" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Item-7" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Item-8" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible NowPlaying" -bool true
defaults write com.apple.controlcenter "NSStatusItem Visible ScreenMirroring" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Shortcuts" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible Sound" -bool false
defaults write com.apple.controlcenter "NSStatusItem Visible WiFi" -bool false


###############################################################################
# Finder
###############################################################################

# Displaying full POSIX path as Finder window title"
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# # Show path bar in Finder"
defaults write com.apple.finder ShowPathbar -bool true

# Always show file extension, and disable the warning when changing a file extension"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false


###############################################################################
# Dock & Mission Control
###############################################################################

# Setting the icon size of Dock items and disabling magnification"
defaults write com.apple.dock tilesize -int 45
defaults write com.apple.dock magnification -bool false
defaults write com.apple.dock largesize -int 45

# # Don't group windows by application in expose"
defaults write com.apple.dock "expose-group-apps" -bool false
defaults write com.apple.dock "show-recents" -bool false

# Setting Dock to auto-hide and removing the auto-hiding delay"
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0


###############################################################################
# Application specific settings
###############################################################################

# None right now


# Note that some of these changes require a logout/restart to take effect."
# Killing some open applications in order to take effect."

find ~/Library/Application\ Support/Dock -name "*.db" -maxdepth 1 -delete
for app in "Activity Monitor" "cfprefsd" \
  "Dock" "Finder" "SystemUIServer"; do
  killall "${app}" > /dev/null 2>&1
done


# Print end
echo ""
print -P "%F{green}✅ MacOS automated setup finished!%f"
echo ""
echo "Run defaults write com.apple.dock persistent-apps -array if you want to empty the dock"
echo ""

